# Application name
name = "Example App"
# External application URL, for non-standard layouts
#url = "https://example.domain.local/"
# HTTP hosts to reply
hosts = ["example.domain.local"]
# Remote target to connect to
remote = "http://192.168.1.10:8080/"
# Compress target responses (brotli)
# The compression is applied automatically to all data.
# Exceptions:
# - image/* (except image/svg, image/svg+xml)
# - video/*
# - audio/*
# - application/zip
# - application/gzip
# - application/x-gzip
# - application/x-7z-compressed
# - application/x-rar-compressed
compress = true
# Client protocol to use, http1.0 for HTTP/1.0, http1 for HTTP/1.1 (default),
# http2 for HTTP/2
#
# - when http1.0 client is used:
#   - no extra headers are inserted (including JWT assertion)
#   - Accept-Encoding and Connection headers are removed
#   - the cookie "gateryx_auth_token" is forcibly removed from Cookie header.
#   - recomended for embedded appliances that do not support HTTP/1.1 properly
#
# - when http2 client is used, the request is not downgraded and sent as-is
#   (the listener must be configured to support HTTP/2)
#
#client = "http1"
# Path to application icon (relative to the primary configuration file)
icon = "icons/generic.png"
# Target timeout (default: 10 seconds)
#timeout = 10
# Application visibility in the list (default: false)
#hidden = false
# Use authentication (default: true)
#use_auth = true
# For remote HTTPS targets, skip TLS verification (default: false)
#skip_remote_tls_verify = false
